"""add number column to pokemons table

Revision ID: 38146763dfbf
Revises: 1df3912d7a30
Create Date: 2025-06-29 14:18:21.364561

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "38146763dfbf"
down_revision: Union[str, Sequence[str], None] = "1df3912d7a30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pokemons", sa.Column("number", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pokemons", "number")
    # ### end Alembic commands ###
